let dados = [
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/ferrari-488-gtb",
        titulo: "Ferrari 488 GTB",
        descricao: "Supercarro italiano com design elegante e motor V8 biturbo. - Acelerada pelo som: A Ferrari 488 GTB possui um sistema de escape variável que altera o som do motor de acordo com o modo de condução, proporcionando uma experiência sonora única e emocionante.",
        potencia: "720 cv",
        preco: "R$ 5.000.000",
        link: "https://autoesporte.globo.com/Fotos/fotos/2015/02/fotos-ferrari-488-gtb.html",
        tags: "ferrari italiano gtb 488 v8 biturbo supercarro super",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/5/51/Ferrari_488_GTB.jpg",
        alt: "Imagem da Ferrari 488 GTB"
    },
    {
        tituloLink: "https://www.lamborghini.com/en-en/models/huracan",
        titulo: "Lamborghini Huracán",
        descricao: "Ícone italiano com motor V10 naturalmente aspirado e desempenho excepcional. - Nome inspirado em touros: Como todos os modelos da Lamborghini, o Huracán recebeu o nome de um touro de luta. Neste caso, o touro Huracán era conhecido por sua força e agilidade.",
        potencia: "640 cv",
        preco: "R$ 4.500.000",
        link: "https://www.guiadoautomovel.pt/marcas/lamborghini/huracan/review",
        tags: "lambo lamborghini italiano v10 aspirado huracán",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Lamborghini_Huracan_Evo_Genf_2019_1Y7A5452.jpg/1200px-Lamborghini_Huracan_Evo_Genf_2019_1Y7A5452.jpg",
        alt: "Imagem da Huracán"
    },
    {
        tituloLink: "https://www.porsche.com/brazil/pt/models/911/911-turbo-models/911-turbo-s/",
        titulo: "Porsche 911 Turbo S",
        descricao: "Esportivo alemão com motor biturbo e aerodinâmica avançada. - Evolução contínua: O Porsche 911 é um dos carros esportivos mais icônicos do mundo e o 911 Turbo S representa o ápice da evolução deste modelo, combinando desempenho e tecnologia de ponta.",
        potencia: "650 cv",
        preco: "R$ 4.800.000",
        link: "https://configurator.porsche.com/pt-BR/model/992450",
        tags: "porsche 911 alemão turbo s biturbo alemão esportivo",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI2O1tzB1okHdB8GkA_Fx7ktRLuC6zN1emrA&s",
        alt: "Imagem da Porsche 911 Turbo S"
    },
    {
        tituloLink: "https://www.rolls-roycemotorcars.com/en_GB/showroom/phantom.html",
        titulo: "Rolls-Royce Phantom",
        descricao: "Sedã de luxo britânico com design clássico e interior opulento. - Luxo artesanal: Cada Rolls-Royce Phantom é construído de forma artesanal, com atenção aos mínimos detalhes. Os clientes podem personalizar seus carros com uma infinidade de opções, tornando cada veículo único.",
        potencia: "571 cv",
        preco: "R$ 10.000.000",
        link: "https://forbes.com.br/forbeslife/forbes-motors/2024/08/rolls-royce-lanca-o-exclusivo-phantom-scintilla-limitado-a-10-unidades/",
        tags: "rolls royce britânico luxo rolls-royce clássico phantom sedã",
        imagem: "https://carrosbemmontados.com.br/wp-content/uploads/2023/09/Rolls-Royce-Phantom-by-MANSORY-1.png",
        alt: "Imagem da Rolls-Royce Phantom"
    },
    {
        tituloLink: "https://www.bentleymotors.com/en/models/continental-gt.html",
        titulo: "Bentley Continental GT",
        descricao: "Grand tourer britânico com motor W12 e acabamento artesanal. - Grand Touring em estado puro: O Bentley Continental GT oferece um equilíbrio perfeito entre luxo, desempenho e conforto, sendo ideal para longas viagens.",
        potencia: "635 cv",
        preco: "R$ 5.500.000",
        link: "https://www.icarros.com.br/bentley/continental-gt/ficha-tecnica/26180",
        tags: "bentley britânico gt grand tourer w12 continental",
        imagem: "https://cdn.motor1.com/images/mgl/gYgQ7/s1/2021-bentley-continental-gt-speed-exterior.webp",
        alt: "Imagem do Bentley Continental GT"
    },
    {
        tituloLink: "https://imprensa.mercedes-benz.com.br/releases/novo-mercedes-benz-s-65-amg-o-desempenho-em-sua-forma-mais-perfeita",
        titulo: "Mercedes-Benz S65 AMG",
        descricao: "Sedã de luxo alemão com motor V12 biturbo e desempenho esportivo. - Potência e sofisticação: O S65 AMG combina a sofisticação da linha S da Mercedes-Benz com a performance de um motor V12 biturbo, oferecendo uma experiência de condução luxuosa e potente.",
        potencia: "630 cv",
        preco: "R$ 3.800.000",
        link: "https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=10551&token=",
        tags: "mercedes benz alemão mercedes-benz v12 esportivo biturbo",
        imagem: "https://quatrorodas.abril.com.br/wp-content/uploads/2016/11/5658c4b5de40d64c20366709mercedes-benz-s65-amg-coupe-1.jpeg?quality=70&strip=all",
        alt: "Imagem da Mercedes-Benz S65 AMG"
    },
    {
        tituloLink: "https://astonmartinworks.com/models/db11/",
        titulo: "Aston Martin DB11",
        descricao: "Grand tourer britânico com design elegante e motor V12 biturbo. - Elegância britânica: O Aston Martin DB11 é um dos carros esportivos mais elegantes do mundo, com um design atemporal e um motor V12 que proporciona um ronco inconfundível.",
        potencia: "600 cv",
        preco: "R$ 4.200.000",
        link: "https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=5691&token=",
        tags: "aston martin britânico v12 grand tourer biturbo",
        imagem: "https://s2-autoesporte.glbimg.com/vIwBZ2bWR8NCS8yuv94v3LkR8vU=/0x0:620x400/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/Q/G/ccW0hJQ7iBfUcysUec7Q/2016-02-29-1-3.jpg",
        alt: "Imagem da Aston Martin DB11"
    },
    {
        tituloLink: "https://cars.mclaren.com/br-pt/super-series/720s",
        titulo: "McLaren 720S",
        descricao: "Supercarro britânico com motor V8 biturbo e aerodinâmica ativa. - Pista nas ruas: A McLaren 720S é um supercarro de pista homologado para uso em vias públicas, oferecendo um desempenho excepcional e uma experiência de condução emocionante.",
        potencia: "720 cv",
        preco: "R$ 5.200.000",
        link: "https://www.mclarensaopaulo.com.br/modelo/mclaren-720s-spider/",
        tags: "britânico mclaren mc laren biturbo v8 supercarro super coupe",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRWQeJvO4NblJZFF5l4CfTbmROBXSqJ9cvXw&s",
        alt: "Imagem da McLaren 720S"
    },
    {
        tituloLink: "https://www.bugatti.com/the-bugatti-models/chiron-facets-of-performance/sport/",
        titulo: "Bugatti Chiron",
        descricao: "Hypercar francês com motor quad turbo e desempenho extremo. - Hypercarro de outro mundo: O Bugatti Chiron é um dos carros mais rápidos e poderosos do mundo, capaz de atingir velocidades superiores a 400 km/h.",
        potencia: "1500 cv",
        preco: "R$ 30.000.000",
        link: "https://exame.com/casual/conheca-o-bugatti-chiron-o-carro-de-r-50-milhoes-que-se-tornou-o-mais-caro-do-brasil/",
        tags: "bugatti chiron hypercarro hyper francês quad turbo",
        imagem: "https://cdn.motor1.com/images/mgl/VzMq0z/s3/bugatti-chiron-1500.jpg",
        alt: "Imagem da Bugatti Chiron"
    },
    {
        tituloLink: "https://www.rolls-roycemotorcars.com/en_US/showroom/cullinan.html",
        titulo: "Rolls-Royce Cullinan",
        descricao: "SUV de luxo britânico com motor V12 e interior opulento. - SUV de luxo extremo: O Cullinan é o primeiro SUV da Rolls-Royce, combinando o luxo e o conforto característicos da marca com a versatilidade de um veículo off-road. Seu nome é uma homenagem ao maior diamante já encontrado.",
        potencia: "571 cv",
        preco: "R$ 12.000.000",
        link: "https://forbes.com.br/forbeslife/2022/03/rolls-royce-cullinan-2022-um-santuario-sobre-rodas/",
        tags: "rolls royce rolls-royce luxo britânico v12",
        imagem: "https://cdn.motor1.com/images/mgl/0bK33/s1/rolls-royce-cullinan.jpg",
        alt: "Imagem do Rolls-Royce Cullinan"
    },
    {
        tituloLink: "https://www.koenigsegg.com/model/jesko-absolut",
        titulo: "Koenigsegg Jesko",
        descricao: "Hipercarro sueco com motor V8 biturbo e desempenho extremo, capaz de ultrapassar os 500 km/h. - Homenagem a um ícone: O Jesko é uma homenagem a Jesko Koenigsegg, o pai fundador da marca. Ele é equipado com um motor V8 biturbo de 5.0 litros capaz de gerar mais de 1.600 cavalos de potência.",
        potencia: "1280 cv",
        preco: "R$ 35.000.000",
        link: "https://carros.ig.com.br/2024-07-04/koenigsegg-jesko--o-carro-mais-rapido-do-mundo-supera-propria-cavalaria-de-1600-cv.html",
        tags: "koenigsegg hipercarro v8 biturbo velocidade maxima sueco hiper",
        imagem: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Koenigsegg_Jesko_Genf_2019_1Y7A5546.jpg/640px-Koenigsegg_Jesko_Genf_2019_1Y7A5546.jpg",
        alt: "Imagem do Koenigsegg Jesko"
    },
    {
        tituloLink: "https://www.dodge.com/bmo.charger.html#/build/exterior/01000/CUD202304LDDP48A/2DN/APA,PR3,X9,EZH,DFK,TR9,WHH,HA,UAS,26N",
        titulo: "Dodge Charger R/T",
        descricao: "Músculo americano clássico, com motor V8 Hemi e design icônico. - Músculo americano: O Charger R/T é um ícone dos muscle cars americanos, conhecido por seu design agressivo e motor V8 potente. Ele é frequentemente associado à cultura pop e ao cinema. - Representante da era de ouro dos muscle cars americanos, o Charger R/T é um símbolo da cultura americana dos anos 60 e 70.",
        potencia: "215 cv (estimativa)",
        preco: "R$ 500.000 (restauração)",
        link: "https://viabella.com.br/carros/classicoscolecao/charger-rt-2",
        tags: "americano dodge charger muscle car v8 classico toretto",
        imagem: "https://www.prathauto.com.br/wp-content/uploads/2021/09/IMG_1026-scaled.jpg",
        alt: "Imagem do Dodge Charger R/T"
    },
    {
        tituloLink: "https://www.nissan.com.br/experiencia-nissan/gt-r.html",
        titulo: "Nissan Skyline GT-R R34",
        descricao: "Lenda japonesa, com motor RB26DETT e tração integral, um dos mais cobiçados da saga. - Lenda japonesa: O Skyline GT-R R34 é um dos carros esportivos japoneses mais icônicos, famoso por sua tração integral e motor turboalimentado. Ele é frequentemente modificado e utilizado em corridas. - É citado em filmes e jogos de corrida, tornando-se um ícone da cultura pop japonesa.",
        potencia: "280 cv (original), mas altamente tunável",
        preco: "R$ 1.500.000 (importado)",
        link: "https://driftforu.com/products/nissan-skyline-r34-gtr-vspec?srsltid=AfmBOorehjNaM_dS4kNhSSExPzFAhqf795B7lMBbt8UgdTnluLQk4DNU",
        tags: "japones nissan skyline gtr r34 rb26dett tunado",
        imagem: "https://store-images.s-microsoft.com/image/apps.18945.71199168177000658.12c8cf1a-ca8b-410e-9bc6-af5b65e03583.26e3bd6f-af7e-4cab-9d3c-ef79c4bfe9d6?q=90&w=480&h=270",
        alt: "Imagem do Nissan Skyline GT-R R34"
    },
    {
        tituloLink: "https://www.webmotors.com.br/carros/estoque/toyota/supra",
        titulo: "Toyota Supra MK4",
        descricao: "Ícone dos anos 90, com motor 2JZ-GTE e visual marcante, popularizado por Brian O'Conner. - Ícone dos anos 90: A Supra MK4 é um dos carros esportivos japoneses mais populares dos anos 90, conhecida por seu design marcante e motor turboalimentado em linha seis cilindros.",
        potencia: "320 cv (original), mas altamente tunável",
        preco: "R$ 800.000 (preparado)",
        link: "https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=2493",
        tags: "japones toyota supra mk4 2jzgte tunado brian",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE-vgK3hKBy5vuiCQesAL4ehRFhQFfWIq_3A&s",
        alt: "Imagem do Toyota Supra MK4"
    },
    {
        tituloLink: "https://www.gtocs.com.br/carros/usado/sao-paulo/mitsubishi/lancer/2.0-evolution-ix-mr-4x4-16v-turbo-intercooler-gasolina-4p-manual-2006/id-106364",
        titulo: "Mitsubishi Lancer Evolution IX",
        descricao: "Rally car japonês, com motor turbo e tração integral, conhecido por sua agilidade e performance. - Rally legendário: O Lancer Evolution IX é um carro de rally homologado para uso em vias públicas, conhecido por seu desempenho em pistas de terra e rally. Ele é frequentemente comparado ao Subaru Impreza WRX STI.",
        potencia: "280 cv (original)",
        preco: "R$ 250.000 (preparado)",
        link: "https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=808",
        tags: "japones mitsubishi lancer evolution ix turbo rally tracao integral",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQgg-5BG62-Ud2Ty3dzCxQZc09As9Sm7Yajg&s",
        alt: "Imagem do Mitsubishi Lancer Evolution IX"
    },
    {
        tituloLink: "https://www.honda.com.br/automoveis/civic-typer",
        titulo: "Honda Civic Type R",
        descricao: "Hatchback esportivo japonês, com motor turbo e suspensão firme. - Hatch: O Civic Type R é um dos hatches esportivos mais populares do mundo, conhecido por sua suspensão firme, direção precisa e motor turbo potente. A sigla 'Type R' é sinônimo de performance na Honda. -  É um ícone da cultura de tuning e um carro popular entre os entusiastas de corridas de rua.",
        potencia: "310 cv (original)",
        preco: "R$ 200.000 (preparado)",
        link: "https://motor1.uol.com.br/news/731978/civic-typer-fica-mais-caro/",
        tags: "japones honda civic type r turbo hatchback tunado",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTN1apQX7bdqa97HGQeB9yA6USs1p1xSCYtA&s",
        alt: "Imagem da"
    },
    {
        tituloLink: "https://www.supercarros.com.br/chevrolet/corvette-c6",
        titulo: "Chevrolet Corvette C6",
        descricao: "Esportivo americano, com motor V8 e design agressivo, símbolo de potência e performance. - Músculo americano moderno: O Corvette C6 é um dos modelos mais icônicos da Chevrolet, oferecendo um equilíbrio entre performance e conforto. Sua estética agressiva e motor V8 potente o tornam um clássico instantâneo.",
        potencia: "400 cv (original)",
        preco: "R$ 350.000 (usado)",
        link: "https://www.icarros.com.br/comprar/sao-paulo-sp/chevrolet/corvette/2023/d47258276?parceiro_id=146&pos=1&hfv=false&financiamento=true",
        tags: "americano chevrolet corvette c6 v8 esportivo",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwdOqsA0xaAnwwCx40Xautz-q0YLWY1Ef2Vw&s",
        alt: "Imagem do Corvette C6"
    },
    {
        tituloLink: "https://www.ford.com.br/performance/mustang/",
        titulo: "Ford Mustang GT",
        descricao: "Músculo americano clássico, com motor V8 potente e design icônico, um dos carros mais populares da saga. - Ícone dos muscle cars: O Mustang GT é um dos muscle cars mais famosos do mundo, conhecido por seu design atemporal. Ele é frequentemente associado à cultura pop e ao cinema. É um símbolo da cultura americana e um dos carros mais modificados do mundo.",
        potencia: "420 cv (original)",
        preco: "R$ 300.000 (usado)",
        link: "https://www.ford.com.br/performance/mustang/gt-performance/",
        tags: "americano ford mustang gt v8 muscle car",
        imagem: "https://originalexperience.com.br/wp-content/uploads/2020/08/mustang-v8.jpg",
        alt: "Imagem do Ford Mustang GT"
    },
    {
        tituloLink: "https://www.lamborghini.com/en-en/history/murcielago-lp-670-superveloce",
        titulo: "Lamborghini Murciélago",
        descricao: "Supercarro italiano, com motor V12 e design exótico, símbolo de luxo e performance.  - Touro lendário: O Murciélago é um dos modelos mais icônicos da Lamborghini, com um design angular e agressivo que o torna inconfundível. Seu nome significa 'morcego' em espanhol, em referência a um touro lendário.",
        potencia: "640 cv (original)",
        preco: "R$ 2.500.000 (usado)",
        link: "https://www.chavesnamao.com.br/carros/brasil/lamborghini-murcielago/",
        tags: "italiano lamborghini murcielago v12 supercarro luxo",
        imagem: "https://cdn.motor1.com/images/mgl/PNllK/s3/lamborghini-murcielago.jpg",
        alt: "Imagem da Lamborghini Murciélago"
    },
    {
        tituloLink: "https://www.wmotors.ae/lykan-hypersport.html",
        titulo: "Lykan Hypersport",
        descricao: "Supercarro árabe, com faróis de diamantes e design futurista, um dos carros mais caros e exclusivos da saga. - Supercarro de luxo: O Lykan Hypersport é um supercarro de luxo árabe, conhecido por seus faróis com diamantes e seu design futurista. Ele apareceu em filmes como 'Velozes e Furiosos 7'.",
        potencia: "770 cv",
        preco: "R$ 15.000.000 (estimativa)",
        link: "https://motor1.uol.com.br/news/114734/carro-mais-caro-do-mundo-supercarro-libanes-lykan-hypersport-custa-r-7-milhoes/",
        tags: "arabe lykan hypersport supercarro luxo exclusivo libânes",
        imagem: "https://carrosbemmontados.com.br/wp-content/uploads/2023/10/Lykan-HyperSport.jpg",
        alt: "Imagem do Lykan Hypersport"
    },
    {
        tituloLink: "https://www.vw.com/en/models/golf-gti.html",
        titulo: "Volkswagen Golf GTI",
        descricao: "Hatchback esportivo alemão, com motor turbo e suspensão firme, conhecido por seu equilíbrio entre performance e praticidade. - Hatch esportivo acessível: O Golf GTI é um dos hatches esportivos mais populares do mundo, conhecido por sua combinação de desempenho, praticidade e preço acessível. Ele é considerado um dos pioneiros do segmento.",
        potencia: "220 cv (original)",
        preco: "R$ 180.000 (usado)",
        link: "https://www.volkswagen.pt/golf/vw-desportivo-golf-gti",
        tags: "alemao volkswagen golf gti turbo hatchback",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq5qD3ZrDTtNVsYe1h63aJu8WBtUtUFpcfNg&s",
        alt: "Imagem do Golf GTI"
    },
    {
        tituloLink: "https://imprensa.renault.com.br/release/item/alpine-a110-legende-gt-2021-o-espirito-gran-turismo-em-sua-versao-mais-intensa/alpine-parte-em-defesa-de-titulos-mundiais",
        titulo: "Renault Alpine A110",
        descricao: "Esportivo leve e ágil, com design clássico e motor turbo, oferecendo uma experiência de condução pura e emocionante.",
        potencia: "252 cv",
        preco: "R$ 250.000 (novo)",
        link: "https://quatrorodas.abril.com.br/noticias/alpine-a110-chega-aos-300-cv-e-ganha-nova-configuracao",
        tags: "frances renault alpine a110 esportivo leve agil",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-7ZCExfN8gW3cWPBSn5pWTB-jWTCnxkLujA&s",
        alt: "Imagem do Renault Alpine A110"
    },
    {
        tituloLink: "https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=135",
        titulo: "Peugeot 504",
        descricao: "Sedã clássico e robusto, conhecido por sua confiabilidade e conforto, com design atemporal.",
        potencia: "110 cv",
        preco: "R$ 50.000 (usado)",
        link: "https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/peugeot/504",
        tags: "frances peugeot 504 sedã clássico",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmVZID0WZU-POJr7kDbG-ySQG-0D3x9GT4Ww&s",
        alt: "Imagem do Peugeot 504"
    },
    {
        tituloLink: "https://jornaldocarro.estadao.com.br/carros/citroen-2cv-icone-da-marca-completa-75-anos-relembre-a-historia/",
        titulo: "Citroën 2CV",
        descricao: "Ícone francês, conhecido por sua simplicidade e versatilidade, com design charmoso e suspensão macia.",
        potencia: "29 cv",
        preco: "R$ 30.000 (usado)",
        link: "https://motorshow.com.br/conheca-o-citroen-2cv-o-carro-que-resistiu-a-segunda-guerra-mundial/",
        tags: "frances citroen 2cv icone simplicidade",
        imagem: "https://www.maxicar.com.br/wp-content/uploads/2022/01/Citroen-2CV-pr.jpg",
        alt: "Imagem do Citroën 2CV"
    },
    {
        tituloLink: "https://www.imprensa.renault.com.br/release/item/novo-megane-rs-275-trophy-potencia-e-exclusividade/pt",
        titulo: "Renault Mégane RS",
        descricao: "Hatchback esportivo francês, conhecido por sua agilidade e direção precisa, com motor turbo e suspensão esportiva.",
        potencia: "280 cv",
        preco: "R$ 150.000 (usado)",
        link: "https://motor1.uol.com.br/news/630591/renault-megame-rs-ultime-despedida/",
        tags: "frances renault megane rs turbo hatchback esportivo",
        imagem: "https://cdn.motor1.com/images/mgl/PRK4A/s1/2018-renault-megane-rs-trophy.jpg",
        alt: "Imagem do Mégane RS"
      },
      {
        tituloLink: "https://www.peugeot.pt/marca-peugeot/universo-peugeot/peugeot-magazine/novo-peugeot-208.html",
        titulo: "Peugeot 208 GTI",
        descricao: "Hatchback compacto e esportivo, com design moderno e motor turbo, oferecendo uma experiência de condução divertida e ágil.",
        potencia: "208 cv",
        preco: "R$ 120.000 (usado)",
        link: "https://motor1.uol.com.br/news/354228/novo-peugeot-208-gti-estreia-em-2020/",
        tags: "frances peugeot 208 gti turbo hatchback compacto",
        imagem: "https://quatrorodas.abril.com.br/wp-content/uploads/2016/11/5658c32f2daad077cb89a0ecpeugeot-208-gti-30th-anniversary-1.jpeg?quality=70&strip=all",
        alt: "Imagem do Peugeot 208 GTI"
      },
      {
        tituloLink: "https://quatrorodas.abril.com.br/carros-usados/guia-de-usados-citroen-ds3ds-3-2011-a-2016",
        titulo: "Citroën DS3",
        descricao: "Hatchback premium com design ousado e personalizável, oferecendo um bom nível de conforto e equipamentos.",
        potencia: "155 cv",
        preco: "R$ 80.000 (usado)",
        link: "https://www.icarros.com.br/comprar/citroen/ds3",
        tags: "frances citroen ds3 premium design",
        imagem: "https://www.blogauto.com.br/wp-content/2010/02/ds3_racing_15.jpg",
        alt: "Imagem do Citroen DS3"
      },
      {
        tituloLink: "https://www.ferrari.com/en-EN/auto/f8-tributo",
        titulo: "Ferrari F8 Tributo",
        descricao: "Sucessor espiritual da 488 GTB, com design ainda mais agressivo.",
        potencia: "720 cv",
        preco: "Consulte a concessionária",
        link: "https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=19376",
        tags: "ferrari f8 tributo v8 biturbo supercarro italiano",
        imagem: "https://s2-autoesporte.glbimg.com/PJVx-woD-SAuruWKPoO1KvmeTfg=/0x0:620x413/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/8/g/Sux9niQ3AYKbeLGaHiAg/2019-02-28-ferrari-f8-tributo-2020-1600-01.jpg",
        alt: "Imagem da Ferrari F8 Tributo"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/ferrari-purosangue",
        titulo: "Ferrari Purosangue",
        descricao: "O primeiro SUV da Ferrari, combinando luxo e performance extrema.",
        potencia: "725 cv",
        preco: "A partir de R$ 7.500.000",
        link: "https://saopaulo.ferraridealers.com/pt-PT/ferrari-purosangue",
        tags: "ferrari purosangue suv v12 luxo performance italiano",
        imagem: "https://s2-autoesporte.glbimg.com/JfR7mAgWhl0UvNaamuflGiYxbHo=/0x0:1920x1080/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2023/X/v/dy9pnBSR2PQUikNdBDEg/sem-titulo.jpg",
        alt: "Imagem da Ferrari Purosangue"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/sf90-stradale",
        titulo: "Ferrari SF90 Stradale",
        descricao: "Hypercar híbrida com motor V8 biturbo e três motores elétricos.",
        potencia: "1000 cv",
        preco: "Cerca de R$ 4.079.000",
        link: "https://quatrorodas.abril.com.br/noticias/ferrari-sf90-xx-e-mais-potente-leve-aerodinamica-e-passa-os-r-4-milhoes",
        tags: "ferrari sf90 stradale hypercar hibrido v8 eletrico italiano hyper supercarro super",
        imagem: "https://quatrorodas.abril.com.br/wp-content/uploads/2023/06/ferrari_sf90_stradale_11-e1688053532954.jpg?crop=1&resize=1212,909",
        alt: "Imagem da Ferrari SF90 Stradale"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/sf90-spider",
        titulo: "Ferrari SF90 Spider",
        descricao: "Versão conversível da SF90 Stradale, com desempenho e tecnologia de ponta.",
        potencia: "1000 cv",
        preco: "R$ 4,5 milhões",
        link: "https://motor1.uol.com.br/reviews/576834/avaliacao-ferrari-sf90-spider/",
        tags: "ferrari sf90 spider hypercar hibrido conversível italiano hyper super supercarro",
        imagem: "https://quatrorodas.abril.com.br/wp-content/uploads/2022/10/NOVITEC-Ferrari-SF90-Spider-1.jpg?crop=1&resize=1212,909",
        alt: "Imagem da Ferrari SF90 Spider, versão conversível da SF90 Stradale"
    },
    {
        tituloLink: "https://saopaulo.ferraridealers.com/pt-PT/296-gtb",
        titulo: "Ferrari 296 GTB",
        descricao: "Supercarro com motor V6 biturbo e tecnologia híbrida plug-in.",
        potencia: "830 cv",
        preco: "R$ 4,5 milhões",
        link: "https://autoesporte.globo.com/lancamentos/noticia/2022/12/ferrari-296-gtb-hibrida-de-830-cv-custa-quase-r-5-milhoes-no-brasil.ghtml",
        tags: "ferrari 296 gtb v6 hibrido plug-in italiano Supercarro",
        imagem: "https://ferrari-cdn.thron.com/delivery/public/image/ferrari/7c9ff38f-4f59-4061-9eaf-f07567430eaf/3zayf6/std/0x415/DWS_ferrari_296_GTB-gallery-1?quality=auto-high&format=auto",
        alt: "Imagem da Ferrari 296 GTB"
    },
    {
        tituloLink: "https://saopaulo.ferraridealers.com/pt-PT/296-gts",
        titulo: "Ferrari 296 GTS",
        descricao: "Supercarro com motor V6 biturbo e tecnologia híbrida plug-in.",
        potencia: "830 cv",
        preco: "R$ 3.490.000,00",
        link: "https://quatrorodas.abril.com.br/noticias/ferrari-296-gts-e-conversivel-v6-hibrido-que-buscar-compensar-falta-do-v12",
        tags: "ferrari 296 gts v6 hibrido plug-in conversível italiano Supercarro",
        imagem: "https://s2-autoesporte.glbimg.com/VA80i3EGTEak0wud9Z1gC2lnyW4=/0x0:1000x682/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2022/E/e/KOncvCSkah99gRDvKwdA/ferrari296gtb.jpg",
        alt: "Imagem da Ferrari 296 GTS"
    },
    {
        tituloLink: "https://saopaulo.ferraridealers.com/pt-PT/812-competizione",
        titulo: "Ferrari 812 Competizione",
        descricao: "Supercarro V12 com desempenho extremo, inspirado nas pistas de corrida.",
        potencia: "830 cv",
        preco: "R$ 15 milhões",
        link: "https://autoesporte.globo.com/lancamentos/noticia/2021/05/nova-ferrari-812-competizione-e-uma-812-superfast-ainda-mais-rapida.ghtml",
        tags: "ferrari 812 competizione v12 supercarro pista italiano",
        imagem: "https://www.topgear.com/sites/default/files/2021/11/812_Competizione_statics-details_10_0.jpg",
        alt: "Imagem da Ferrari 812 Competizione"
    },
    {
        tituloLink: "https://saopaulo.ferraridealers.com/pt-PT/812-competizione",
        titulo: "Ferrari 812 Competizione Spider",
        descricao: "Versão conversível da 812 Competizione, com desempenho e emoção a céu aberto.",
        potencia: "830 cv",
        preco: "R$ 3.162.000,00.",
        link: "https://autoesporte.globo.com/lancamentos/noticia/2021/05/nova-ferrari-812-competizione-e-uma-812-superfast-ainda-mais-rapida.ghtml",
        tags: "ferrari 812 competizione spider v12 conversível hypercar hyper super italiano",
        imagem: "https://cdn.ferrari.com/cms/network/media/img/resize/608c1cba09d0115feb7ef6a9-ferrari-812-competizione-a--design-focus?",
        alt: "Imagem da Ferrari 812 Competizione Spider, versão conversível da 812 Competizione"
    },
    {
        tituloLink: "https://saopaulo.ferraridealers.com/pt-PT/ferrari-roma",
        titulo: "Ferrari Roma",
        descricao: "Grand Tourer com design elegante e motor V8 biturbo, ideal para longas viagens.",
        potencia: "620 cv",
        preco: "R$ 3.950.000",
        link: "https://autoesporte.globo.com/carros/testes-de-carros/review/2024/09/teste-ferrari-roma-spider-dirigir-de-cabelo-ao-vento-nunca-foi-tao-bom.ghtml",
        tags: "ferrari roma v8 grand tourer italiano luxo",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3qD5kEVqSFMIVj26VYtWzltwCeXOEofDyTQ&s",
        alt: "Imagem da Ferrari Roma"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/ferrari-roma-spider",
        titulo: "Ferrari Roma Spider",
        descricao: "Versão conversível da Ferrari Roma, combinando elegância e desempenho a céu aberto.",
        potencia: "620 cv",
        preco: "R$ 3.950 milhões",
        link: "https://autoesporte.globo.com/carros/testes-de-carros/review/2024/09/teste-ferrari-roma-spider-dirigir-de-cabelo-ao-vento-nunca-foi-tao-bom.ghtml",
        tags: "ferrari roma spider v8 conversível italiano super luxo",
        imagem: "https://cdn.motor1.com/images/mgl/0eVzKk/s1/ferrari-roma-spider-cropped.webp",
        alt: "Imagem da Ferrari Roma Spider, versão conversível da Ferrari Roma"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/laferrari-aperta",
        titulo: "LaFerrari Aperta",
        descricao: "Hypercar híbrida com teto retrátil, combinando performance extrema e exclusividade.",
        potencia: "963 cv",
        preco: "R$ 14.000.000,00",
        link: "https://autopapo.com.br/ferrari/laferrari-aperta/",
        tags: "ferrari laferrari aperta hypercar hibrido italiano teto-retratil hypercar hyper super",
        imagem: "https://quatrorodas.abril.com.br/wp-content/uploads/2017/06/laferrari-aperta-e1498583900690.jpg?crop=1&resize=1212,909",
        alt: "Imagem da Ferrari LaFerrari Aperta, hypercar híbrida com teto retrátil"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/laferrari",
        titulo: "LaFerrari",
        descricao: "Hypercar híbrida com desempenho excepcional, limitada a apenas 500 unidades.",
        potencia: "963 cv",
        preco: "R$ 36.208.523,00",
        link: "https://quatrorodas.abril.com.br/noticias/unica-ferrari-laferrari-do-brasil-tera-o-ipva-mais-caro-de-2024",
        tags: "ferrari laferrari hypercar hibrido italiano limitada",
        imagem: "https://www.webmotors.com.br/wp-content/uploads/2022/03/05073059/274188655_526833631996066_8972501954140295031_n.jpg",
        alt: "Imagem da Ferrari LaFerrari, hypercar híbrida"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/enzo-ferrari",
        titulo: "Enzo Ferrari",
        descricao: "Hypercar em homenagem a Enzo Ferrari, com motor V12 atmosférico e performance excepcional.",
        potencia: "660 cv",
        preco: "Cerca de R$ 19 milhõe",
        link: "https://autoesporte.globo.com/carros/noticia/2020/06/ferrari-enzo-e-arrematada-por-r-129-milhoes-na-internet-e-quebra-recorde-historico-de-leilao-online.ghtml",
        tags: "ferrari enzo hypercar v12 italiano homenagem hyper",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmYTe6bQQtji7MasMdFX7S4txCMpEkEbprhw&s",
        alt: "Imagem da Ferrari Enzo, homenagem a Enzo Ferrari"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/f50",
        titulo: "F50",
        descricao: "Supercarro com motor V12 atmosférico, celebrando os 50 anos da Ferrari.",
        potencia: "520 cv",
        preco: "R$ 27,9 milhões",
        link: "https://autoesporte.globo.com/curiosidades/noticia/2022/08/rarissima-ferrari-f50-que-foi-de-mike-tyson-deve-ser-vendida-por-r-30-milhoes-em-leilao.ghtml",
        tags: "ferrari f50 v12 italiano aniversario supercarro super",
        imagem: "https://www.automaistv.com.br/wp-content/plugins/seox-image-magick/imagick_convert.php?width=1200&height=627&format=.jpg&quality=91&imagick=/wp-content/uploads/2022/11/F50-1-1200x720.jpg",
        alt: "Imagem da Ferrari F50, celebrando os 50 anos da Ferrari"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/f40",
        titulo: "F40",
        descricao: "Ícone dos supercarros, com motor V8 biturbo e construção leve.",
        potencia: "478 cv",
        preco: "R$ 3.900.000,00 - porém pode variar bastante. Exemplares especiais podem valter até 10x mais do que o preço inicial",
        link: "https://www.instacarro.com/blog/mercado-automotivo/ferrari-f40",
        tags: "ferrari f40 v8 biturbo italiano icone super supercarro",
        imagem: "https://s2-autoesporte.glbimg.com/bJzM8q1HFgYZA61OxG7NmiDsKOw=/0x0:1920x1244/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2023/B/k/9exR2VQJCHzdaxWxGJGQ/ferrari-toto-1.jpg",
        alt: "Imagem da Ferrari F40, ícone dos supercarros"
    },
    {
        tituloLink: "https://www.ferrari.com/en-EN/auto/gto",
        titulo: " Ferrari GTO",
        descricao: "Versão de competição da 288 GTO, com motor V8 biturbo e aerodinâmica aprimorada. A Ferrari 250 GTO é comparada a algumas das obras de arte mais exclusivas do mundo, como 'Os Girassóis' de Van Gogh",
        potencia: "400 cv",
        preco: "O preço de um Ferrari 250 GTO pode variar bastante, dependendo do modelo e das condições em que se encontra - Uma Ferrari 250 GTO rara está à venda e o preço deve passar de R$ 150 milhões.",
        link: "https://autopapo.com.br/curta/ferrari-250-gto-venda/",
        tags: "ferrari gto v8 biturbo italiano competicao",
        imagem: "https://www.amalgamcollection.com/cdn/shop/files/Wideedit_c75f3823-4d44-4c28-98e9-9ae08f7486e0_2000x850_crop_center.jpg?v=1706011400",
        alt: "Imagem da Ferrari GTO, versão de competição da 288 GTO"
    },
    {
        tituloLink: "",
        titulo: "McLaren F1",
        descricao: "Considerada por muitos como um dos melhores carros esportivos de todos os tempos, com um motor V12 central e uma distribuição de peso quase perfeita.",
        potencia: "",
        preco: "",
        link: "",
        tags: "",
        imagem: "",
        alt: ""
    },
    {
        tituloLink: "",
        titulo: "Porsche 911 GT1",
        descricao: "Uma máquina de corrida homologada para uso em vias públicas, com um design aerodinâmico extremo e um motor boxer de seis cilindros turboalimentado.",
        potencia: "",
        preco: "",
        link: "",
        tags: "",
        imagem: "",
        alt: ""
    },
    {
        tituloLink: "",
        titulo: "",
        descricao: "",
        potencia: "",
        preco: "",
        link: "",
        tags: "",
        imagem: "",
        alt: ""
    },
    {
        tituloLink: "",
        titulo: "",
        descricao: "",
        potencia: "",
        preco: "",
        link: "",
        tags: "",
        imagem: "",
        alt: ""
    },
];